<br><br><br><title>BETA - Dashboard</title>


<div class="project-container">
<?php
	$identifier=true;
	//-query  the database table 
	$sql="SELECT * FROM projects WHERE public LIKE '%" . $identifier . "%'"; 
	//-run  the query against the mysql query function 
	$result=mysql_query($sql);
	//-create  while loop and loop through result set 
	while($row=mysql_fetch_array($result)){ 
		$project_id=$row['project_id'];
		$project_owner=$row['project_owner'];
		$project_name=$row['project_name'];
		$project_description_short=$row['project_description_short'];
		$project_description=$row['project_description'];
		
		if(!isset($project_description_short)){
			$about="<i>This project has no short description.</i>";
		}
		
		if ($project_owner==$user_id){
			$custom1 = "You own this";
		}
		
		echo "
			<a  class='search-result' href='project.php?project=$project_id'>
				<h1 class='text'>$project_name</h1>
				<p class='text'>$custom1</p>
			</a>
				<p class='about'>$project_description_short</p>
		";
	}

?>

</div>