<br><br><br>

<?php
	$user = $_GET['user'];
	
	$res=mysql_query("SELECT * FROM users WHERE user_id='$user'");
	$row=mysql_fetch_array($res);
?>


<div id="about">
	<p style="float:left; width:830px;"><?php echo $row['about']; ?></p>
</div>

<div style="width:150px; height:180px; float:right;" id="profile-picture-container">
	<img style="float:left;" src="<?php echo $row['picture']; ?>" height="150px" width="150px">
</div>